---

- name: copy nginx config dir
  copy: 
    src=../files/nginx_config_dir/ 
    dest=/etc/nginx/
    directory_mode=yes
    mode: '0755'
    register: nginxconfdir
   
- name: Restart nginx on config change
  ansible.builtin.systemd:
    state: restarted
    name: nginx.service
  when: nginxconfdir.changed
