---

- name: Synchronization of src on the control machine to dest on the remote hosts
  ansible.posix.synchronize:
    src: ../files/nginx_config_dir/ 
    dest: /etc/nginx/
    owner: yes
    perms: yes
  register: nginxconfdir
   
- name: Restart nginx on config change
  ansible.builtin.systemd:
    state: restarted
    name: nginx.service
  when: nginxconfdir.changed
