---

- name: Disable SSH password authentication
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^#?\s*PasswordAuthentication\s'
    line: 'PasswordAuthentication no'
    state: present
  become: true
  register: sshd
  
- name: Restart SSH Daemon on config change
  ansible.builtin.systemd:
    state: reloaded
    name: ssh.service
  when: sshd.changed
