---

- name: Install packages if Debian based
  apt:
    name: "{{ lookup('file', '../package_list.txt').split() }}"
    state: present
    update_cache: true
  become: true
  when: ansible_os_family == 'Debian'

- name: Set up Repositories
  include_tasks: repositories.yml   
 
- name: Install Matrix Server packages
  apt:
    name: "{{ lookup('file', '../package_list_matrix_required.txt').split() }}"
    state: present
    update_cache: true
  become: true
  when: ansible_os_family == 'Debian'
