---

- name: Add Synapse Server Repo Key
  ansible.builtin.apt_key:
    url: https://packages.matrix.org/debian/matrix-org-archive-keyring.gpg
    state: present
    keyring: /usr/share/keyrings/matrix-org-archive-keyring.gpg

- name: Figure out distribution release via lsb_release
  shell: lsb_release -c -s
  register: distributionrelease

- name: Set variable "distributionrelease" for the next step
  set_fact: distributionrelease={{ distributionrelease.stdout }}
    
- name: Add Synapse Server Repo
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/matrix-org-archive-keyring.gpg] https://packages.matrix.org/debian/ {{ distributionrelease }} main"
    state: present
    update_cache: no
    filename: matrix-repo
